name: Deploy Backend

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '18'

    - name: Transfer Selected Files to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          scp -P ${{ secrets.PORT }} -i ${{ secrets.SSH_PRIVATE_KEY }} ./backend/{cognito.js,index.js,package-lock.json,package.json,.env} ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/var/www/arentals/backend-dist
          ssh -p ${{ secrets.PORT }} -i ${{ secrets.SSH_PRIVATE_KEY }} ${{ secrets.USERNAME }}@${{ secrets.HOST }} <<EOF
            cd /var/www/arentals/backend-dist
            npm install
            pm2 restart all
          EOF
