name: Deploy Frontend

on:
  push:
    branches:
      - prod

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16' # Adjust based on your Vue.js project requirements

    - name: Install Dependencies
      run: npm install

    - name: Build
      run: npm install && npm run build
      working-directory: ./frontend

    - name: Archive Build Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist/

    - name: Deploy to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        port: ${{ secrets.PORT }}
        source: "dist/*"
        target: "/var/www/html"

    - name: Reload Nginx
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          sudo systemctl reload nginx
