name: Deploy to EC2

on:
  push:
    branches: [ prod ]  # Trigger on push to 'prod' branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build Application
        run: |
          cd frontend # Change the working directory to frontend
          npm install  # Install dependencies locally
          npm run build  # Build the project (assuming it creates a 'dist' directory)

      - name: Upload Project Files (Frontend & Backend)
        uses: easingthemes/ssh-deploy@v2.1.5 
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-vrz --delete"  # Flags for recursive upload, remove old files
          SOURCE: "."  # Upload the entire project directory
          REMOTE_HOST: "18.216.109.114"  
          REMOTE_USER: "ec2-user"   # Adjust if your EC2 user is different
          TARGET: "~/bostonrentals"  

      - name: Install and Build on EC2 (Backend Only)
        uses: appleboy/ssh-action@master
        with:
          host: "18.216.109.114"
          username: "ec2-user"   # Adjust if necessary
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            cd ~/bostonrentals/backend
            npm install  # Install dependencies on the server

