name: Deploy to EC2

on:
  push:
    branches: [ prod ]  # Trigger on push to 'prod' branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build Application
        run: |
          cd frontend # Change the working directory to frontend
          npm install  # Install dependencies locally
          npm run build  # Build the project (assuming it creates a 'dist' directory)

      - name: Upload Project Files (Frontend)
        uses: easingthemes/ssh-deploy@v2.1.5 
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-vvvrz --exclude 'frontend/node_modules'"  # Extended logging, exclude node_modules.
          SOURCE: "frontend/dist"  # Upload the frontend/dist directory
          REMOTE_HOST: "18.119.120.153"  
          REMOTE_USER: "ec2-user"   
          TARGET: "~/bostonrentals/frontend/dist"  

      - name: Upload Project Files (Backend)
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-vvvrz --exclude 'backend/node_modules'" # Exclude node modules, extended logging.
          SOURCE: "backend" # Upload the backend directory
          REMOTE_HOST: "18.119.120.153"
          REMOTE_USER: "ec2-user" 
          TARGET: "~/bostonrentals/backend"

      - name: Install and Build on EC2 (Backend Only)
        uses: appleboy/ssh-action@master
        with:
          host: "18.119.120.153"
          username: "ec2-user"   # Adjust if necessary
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/bostonrentals/backend
            npm install  # Install dependencies on the server

